- name: Run trivy with reviewdog
  # You may pin to the exact commit or the version.
  # uses: reviewdog/action-trivy@53df306f280cda70854ce997d97759e53c0e3abe
  uses: reviewdog/action-trivy@v1.9.0
  with:
    # GITHUB_TOKEN
    github_token: # default is ${{ github.token }}
    # Directory to run the action on, from the repo root.
Default is . ( root of the repository)

    working_directory: # optional, default is .
    # Report level for reviewdog [info,warning,error]
    level: # optional, default is error
    # The name for the report as it will show up in GitHub's interface.
Default is trivy.

    tool_name: # optional, default is trivy
    # Reporter of reviewdog command [github-pr-check,github-pr-review].
Default is github-pr-check.

    reporter: # optional, default is github-pr-check
    # Filtering for the reviewdog command [added,diff_context,file,nofilter].
Default is added.

    filter_mode: # optional, default is added
    # Exit code for reviewdog when errors are found [true,false]
Default is `false`.

    fail_on_error: # optional, default is false
    # Additional reviewdog flags
    flags: # optional, default is 
    # Trivy command [aws,config,filesystem,image,kubernetes,rootfs,sbom,vm]

    trivy_command: 
    # Trivy target to scan

    trivy_target: 
    # The version of trivy to install.
Default is latest.

    trivy_version: # optional, default is latest
    # List of arguments to send to trivy
For the output to be parsable by reviewdog --format=checkstyle is enforced
Default is blank.

    trivy_flags: # optional, default is 
          
