name: Claude Code Action

on:
  issue_comment:
    types: [created, edited]
  pull_request_target:
    types: [opened, synchronize, reopened, edited]

jobs:
  claude:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 20  # 建议设置以获取完整git历史
          
      - name: Claude Code Action
        uses: anthropics/claude-code-action@v0.0.31
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_AUTH_TOKEN }}
          ANTHROPIC_API_BASE: ${{ secrets.ANTHROPIC_BASE_URL }}



